# pip install pyyaml
# pip install pytest==4.5.0
# pip install tavern

test_name: login_get

# marks:
#   - skip

stages:
  - name: Make get request
    request:
      url: "{url}"
      method: GET
    response:
      status_code: 200
---
test_name: login_post

# marks:
#   - usefixtures:
#     - logging

stages:
  - name: Make a successful login request
    request:
      url: "{url}"
      method: POST
      data:
        username: admin
        password: abc123
        age: 18
        sex: F
    response:
      status_code: 200
      json:
        username: "{tavern.request_vars.data.username}"
        age: 18
        password: abc123
        sex: F
---
test_name: login_wrong_sex
stages:
  - name: test_login_002
    request:
      url: "{url}"
      method: POST
      data:
        username: admin
        password: abc123
        age: 18
        sex: X
    response:
      status_code: 400
      json:
        message:
          sex: sex is wrong
---
test_name: login_wrong_name
marks:
  - smoke
stages:
  - name: test_login_003
    request:
      url: "{url}"
      method: POST
      data:
        password: abc123
        age: 18
        sex: F
    response:
      status_code: 400
      json:
        message:
          username: username is wrong
  - name: Success login after first faliure
    request:
      url: "{url}"
      method: POST
      data:
        username: admin
        password: abc123
        age: 18
        sex: F
    response:
      status_code: 200
      json:
        username: admin
        age: 18
        password: abc123
        sex: F
---
test_name: login_wrong_age

marks:
  - parametrize:
      key: age
      vals:
        - abc
        - None
stages:
  - name: test_login_003
    request:
      url: "{url}"
      method: POST
      data:
        username: admin
        password: abc123
        age: "{age}"
        sex: F
    response:
      status_code: 400
      json:
        message:
          age: age must be int
